kafka:
  bootstrap_servers: "localhost:9092"
  topic: "log-topic"
  group_id: "log-consumer-group"

mysql:
  host: "localhost"
  port: 3306
  user: "python"
  password: "python#123"
  database: "log_analysis"

log:
  file_path: "./resources/data/logs/apache.log"

ai:
  enabled: true
  openai_api_key: "P1CxVPHZhfSZgBoPZJPJ9zoG2c7KwIg+7RRkjjionqT0D4Z+MKwUJ5ybJfPr+bTCu19Kyr1J99AKvFLW1sz4FRzsKs3nZ3IQS0HlT8U7wGodpU3cxvvzWH7O84hFleYoN9RTfNB4iX7rMQFp+tmuo7M0KoyxD0jRliCSIoL4BfU6/S+73zUSuDwT4VaDAsT39EQus4UcaSe7d5dLDtRYeM5cFAPAxVhXgNo0RdJeQRJ8/7/DOBYOnBp3f3GSnzCA"

general:
  environment: "dev"
